spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 961028
    url: jdbc:mysql://localhost/wechat?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
    context-path: /sell

wechat:
  mpAppId: wxbd411b9ed8302b87
  mpAppSecret: 70240bc9a8794ed5e64ed5337a794d50

